Issue-2-view-entries
ChorongShin/code-journal pull request #6
Opened 2022-05-31 06:49 UTC by ChorongShin

https://user-images.githubusercontent.com/91721272/171109941-5b503795-51a1-436e-a3b9-b3b6bf155e70.mov

2022-05-31 17:06 UTC, Zhiwutian requested changes
update needed.

2022-05-31 17:06 UTC, Zhiwutian commented on js/main.js
> +  window.location.reload();
you cannot reload the application during run time to update the DOM. Instead, you want to read through the hints about using the `prepend` method to add the new entry to the DOM when the form is submitted. Make sure to reach out with any questions!

2022-05-31 17:50 UTC, ChorongShin commented
https://user-images.githubusercontent.com/91721272/171252344-2fdd2467-ebe9-494f-862f-d8217d227d1c.mov

2022-06-01 00:50 UTC, ChorongShin commented
https://user-images.githubusercontent.com/91721272/171306543-98217afa-444b-4328-b241-abe077623f5a.mov

2022-06-01 00:53 UTC, Zhiwutian approved these changes
👍🏼

2022-06-01 00:53 UTC, merged